---
general:
  buildTool: "npm"
service:
  buildToolVersion: "N14"
  cloudConnectors:
    transportRequestUploadCTS:
      credentialId: "integration-cc"
stages:
  Build:
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false
  Malware Scan:
    malwareExecuteScan: false
  Compliance:
    sonarExecuteScan: false
  Release:
    transportRequestUploadCTS: true
steps:
  npmExecuteLint:
    failOnError: false
  npmExecuteScripts:
    runScripts:
    - "test"
  sonarExecuteScan:
    mode: ""
    serverUrl: ""
    organization: ""
    projectKey: ""
    sonarTokenCredentialsId: ""
  transportRequestUploadCTS:
    endpoint: "https://github.com/mingkho/mkstdfioriapp1.git"
    uploadCredentialsId: "abap-credential"
    abapPackage: "ZSGPACK"
    applicationName: "ZMKSTDFIORIAPP1"
    applicationDescription: "MKSTDFIORIAPP1"
    transportRequestId: "JA1K900037"
